# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02293fddb3dcb789f862db55209f1531a256651c56d2ee6634097dd52a7bc281551add438d1b2e69737f2b626978c942771d09e540b84d76fa37170d8fff0693

test:
  secret_key_base: c2bdb294d7dc31dd8e59526cadd1ea7c5a52b7662e8b595bba0ba272ec30905ba0eea1b1690fa41ae05d31575468296492c56a6a949d8b3495bf516d16df7203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
